# Generated by Django 4.1 on 2022-08-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muallif',
            old_name='tugatil_y',
            new_name='t_y',
        ),
        migrations.AlterField(
            model_name='muallif',
            name='kitob_soni',
            field=models.IntegerField(),
        ),
    ]
